version: 2
jobs:
  build:
    docker:
        - image: circleci/rust:1.32

    steps:
        - checkout

        - run:
            name: build
            command: cargo build

        - run:
            name: test
            command: cargo test

        - run:
            name: doc
            command: cargo doc
